### ISSUE TITLE
Webhook integration should not hardcode clear property

### ISSUE THREAD

**Issue by collinvandyck** [librato/librato-services#132]
When the clear comes in, the webhook renders it always as `normal`. However, this could be one of `normal`, `auto`, or `manual`, based on the incoming payload. See how other services distinguish here for an example.

https://github.com/librato/librato-services/blob/768fdb82c8e483d407aaef5ca1d071fe898d0d8a/services/webhook.rb#L43

cc @jderrett @obfuscurity

**Comment by obfuscurity** [comment]
FYI, It looks like SNS and OpsGenie are also hardcoded to `normal`.
